# EiffelStudio Community releases
# Copyright (C) 2021  Louis M
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA


FROM ubuntu:18.04

LABEL maintainer="Louis M <eiffel@tioui.com>"

ADD ./build /home/eiffel

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends --no-install-suggests \
        ca-certificates curl \
        bzip2 \
        gcc make dist \
        libxtst-dev \
        libgtk2.0-dev \
        libgtk-3-dev \
        libgdk-pixbuf2.0-dev \
        libssl-dev \
        libcurl4-openssl-dev \
		pax \
        dos2unix \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
	&& mkdir /home/eiffel/Output


#Define delivery variables
ENV ISE_PLATFORM=linux-x86-64

#ENV ONLY_PORTERPACKAGE=true

WORKDIR /home/eiffel/
RUN dos2unix /home/eiffel/build_porterpackage.sh
CMD /bin/bash /home/eiffel/build_porterpackage.sh
